### ISSUE TITLE
How to specify native dll and custom file to remote?

### ISSUE THREAD

**Issue by soloman817** [MSRCCS/Prajna#148]
In your paper, it says there can be non-assembly files uploaded, but I cannot find any example how to do that? any help? sorry, new to Prajna, but it is cool :)

**Comment by msrccsbuild** [comment]
An example of include 3rd party assembly file is:

In which you can call unmanaged DLLs at remotely.

https://github.com/MSRCCS/Prajna/blob/master/samples/DistributedSort/DistributedSort.fs

Generally, the remoting of files use the pattern:

let curJob = JobDependencies.setCurrentJob remoteJobName
curJob.AddDataDirectory( localDepsDirToDistribute ) |> ignore

the Directory entry can include both data files and unmanaged dlls, and you can
include multiple directory entries.

E.g.,

curJob.AddDataDirectoryWithPrefix( null, rootdir, "root", "*", SearchOption.AllDirectories )

will add a local directory pointed by rootdir to remote. At remote, the directory will be at:

CurrentDirection\"root"[Local Direcotory]

You can also use,

curJob.EnvVars.Add(DeploymentSettings.EnvStringSetJobDirectory, depDirName )

to add Environment Variable entry to remote. We find it sometime necessary to properly remote the CUDA environment.

Let me know if you have additional questions.

Best,
Jin
