### ISSUE TITLE
app.config is lost in remote

### ISSUE THREAD

**Issue by soloman817** [MSRCCS/Prajna#149]
I tried to use app.config to configure some stuff of my application, which contains a configSection. But this doesn't work, and then I check the file in `C:\Prajna\Job1082\MyApp\XXXX`, the app.config is a totally new one, which just add some `FSharp.Core` binding. Is this a bug? or should this be fixed?

**Comment by msrccsbuild** [comment]
Can you please send me the appconfig file that you plan to remote and the one that is generated by Prajna. Let me work to fix the issue.

Thanks,
Jin

**Comment by soloman817** [comment]
Hi Jin,

Thanks for your quick reply. I created a x64 console application, and the app.config is:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <section name="aleaSettings" type="Alea.Settings, Alea"/>
    </configSections>
    <aleaSettings>
        <resource path="C:\Prajna\Alea" assemblyPath="C:\Prajna\Alea"/>
        <!--<jitCompile level="Diagnostic"/>
        <diagnostics trace="true" innerException="true" saveIR="false" savePTX="false"/>
        <diagnostics trace="false" innerException="true" saveIR="false" savePTX="false"/>
        <diagnostics trace="true" innerException="false" saveIR="true" savePTX="true"/>-->
        <memory allowNonBlittableMemoryTransfer="true"/>
    </aleaSettings>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
</configuration>
```

So it is the most simple .NET configuration usage, just not the basic `appSetting`, it is a custom config section.

BTW, I also have a workaround on the native stuff uploading, it works like:
- I embedded native dlls into an assembly
- I reference these assembly in Prajna client
- I extract the native dlls from the assembly resource in the remote and try to reuse them

for example, in the folder `C:\Prajna\Job1082\PrajnaTest.CS\XXXXXX`, I will have assemblies like:
- PrajnaTest.CS.exe
- Alea.Native1.dll
- Alea.Native2.dll

Then after the client running, there will be some sub folder created like:
- Alea.Native1 folder
- Alea.Native2 folder
- PrajnaTest.CS.exe
- Alea.Native1.dll
- Alea.Native2.dll

This works, but I want to ask opioion from you, will those temp created folder be erased each time when this assembly in remote is reused? or you will not cleanup the remote folder?

Regards,
Xiang.

**Comment by jinlmsft** [comment]
I am checking in a change that will fix the App Configuration issue. I tried your configuraton setting, and it should be remoted. 

The changeset is being verified, and once the build pass, I will merge the change into the main branch. 

During the interim, you can use:

https://github.com/jinlmsft/Prajna/commit/d682628f82cabee1a0c5057fb3f5612fdc0c3c6f

to try to see if it fix your configuration issue. 

Please note that this is a change that needs an updated Daemon. So if you have deployed any remote daemon, it will need to be redeployed. 

Best, 
Jin
